<?php

namespace Yami\Assessments\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class AssessmentsDemoSeeder extends Seeder
{
    public function run(): void
    {
        if (!config('assessments.enabled')) {
            $this->command?->warn('Assessments are disabled. Enable them to browse demo data.');
        }

        DB::transaction(function () {
            // Topic
            $topicId = DB::table('assessment_topics')->insertGetId([
                'name' => 'Basics',
                'slug' => 'basics',
                'description' => 'Demo topic for Assessments',
                'is_active' => true,
                'position' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Helper to create a choice question with inline Answer Set items
            $makeQuestion = function (string $slug, string $text, array $answers, array $correctIdxs, string $explanation) use ($topicId) {
                $qid = DB::table('assessment_questions')->insertGetId([
                    'slug' => $slug,
                    'text' => $text,
                    'response_type' => 'single_choice',
                    'weight' => 2,
                    'difficulty' => 'easy',
                    'is_active' => true,
                    'note_enabled' => false,
                    'note_required' => false,
                    'note_hint' => null,
                    'explanation' => $explanation,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                DB::table('assessment_question_topics')->insert([
                    'question_id' => $qid,
                    'topic_id' => $topicId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                // Create a private Answer Set for the question
                $setId = DB::table('assessment_answer_sets')->insertGetId([
                    'name' => 'Question '.$qid.' Set',
                    'slug' => 'q-'.$qid,
                    'description' => 'Auto-generated by demo seeder',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                $keepItemIds = [];
                foreach ($answers as $i => $label) {
                    $itemId = DB::table('assessment_answer_set_items')->insertGetId([
                        'answer_set_id' => $setId,
                        'label' => $label,
                        'value' => null,
                        'position' => $i + 1,
                        'is_active' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                    $keepItemIds[] = $itemId;

                    DB::table('assessment_question_answer_links')->insert([
                        'question_id' => $qid,
                        'answer_set_item_id' => $itemId,
                        'position' => $i + 1,
                        'is_active' => true,
                        'is_correct' => in_array($i + 1, $correctIdxs, true),
                        'label_override' => null,
                        'value_override' => null,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);

                    $key = Str::slug(mb_substr($label, 0, 32)) ?: 'option';
                    $dup = 1; $optKey = $key;
                    while (DB::table('assessment_question_options')->where('question_id', $qid)->where('key', $optKey)->exists()) {
                        $optKey = $key.'-'.($dup++);
                    }

                    $optId = DB::table('assessment_question_options')->insertGetId([
                        'question_id' => $qid,
                        'answer_set_item_id' => $itemId,
                        'label' => $label,
                        'key' => $optKey,
                        'position' => $i + 1,
                        'is_active' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);

                    if (in_array($i + 1, $correctIdxs, true)) {
                        DB::table('assessment_answer_keys')->insert([
                            'question_id' => $qid,
                            'option_id' => $optId,
                            'answer_set_item_id' => $itemId,
                            'created_at' => now(),
                            'updated_at' => now(),
                        ]);
                    }
                }

                return $qid;
            };

            $q1 = $makeQuestion('q-1', 'What is 2+2?', ['3', '4'], [2], 'Basic arithmetic: 2 + 2 always equals 4.');
            $q2 = $makeQuestion('q-2', 'Capital of France?', ['London', 'Paris'], [2], 'Paris is the capital and most populous city of France.');

            // Exam (manual)
            $examId = DB::table('assessment_exams')->insertGetId([
                'title' => 'Demo Exam',
                'slug' => 'demo-exam',
                'assembly_mode' => 'manual',
                'is_published' => true,
                'status' => 'published',
                'shuffle_questions' => true,
                'shuffle_options' => true,
                'show_explanations' => true,
                'pass_type' => 'percent',
                'pass_value' => 50,
                'max_attempts' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('assessment_exam_questions')->insert([
                ['exam_id' => $examId, 'question_id' => $q1, 'position' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['exam_id' => $examId, 'question_id' => $q2, 'position' => 2, 'created_at' => now(), 'updated_at' => now()],
            ]);

            // Exam (by_count)
            DB::table('assessment_exams')->insert([
                'title' => 'Quick Check',
                'slug' => 'quick-check',
                'assembly_mode' => 'by_count',
                'question_count' => 2,
                'is_published' => true,
                'status' => 'published',
                'shuffle_questions' => true,
                'shuffle_options' => true,
                'pass_type' => 'percent',
                'pass_value' => 50,
                'max_attempts' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        $this->command?->info('Assessments demo data seeded: Topic, 2 Questions, 2 Exams (manual + by_count).');
    }
}
